name: Brian Chuk
title: 'Brian Chuk'
tagline: Brian Chuk
description: Software Engineer
url: http://devchuk.github.io

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Permalinks
permalink: /blog/:title/

repo: https://github.com/devChuk.github.io

# Portfolio Setup
collections:
  projects:
    output: true

exclude:          [./_posts/new.py, ./_projects/new.py]